- name: Copy file from local to remote clients
  hosts: all

  tasks:
  - name: Copying files
    become: true
    copy:
     src: /home/vagrant/some.cfg
     dest: /tmp
     owner: vagrant
     group: vagrant
     mode: 0644