--- 
- name: create a file and add text
  hosts: localhost

  tasks:
  - name: Create a file 
    file: 
     path: /tmp/george
     state: touch 

  - name: Add text to file 
    blockinfile: 
     path: /tmp/george
     block: George is one of the main character of Seinfled show and he is Jerry's best friend.