---
- name: Install httpd package
  yum: 
    name: httpd
    state: present

- name: start httpd
  service: 
    name: httpd
    state: started

- name: Open port for http
  firewalld: 
  service:
    name: firewalld
    state: reloaded