# the file to be executed must be in the client server(s)
---
- name: Create a cron job
  hosts: all
  tasks:
    - name: Schedule cron
      cron:
        name: THis job is scheduled by Ansible 
        minute: '0'
        hour: '10'
        day: '*'
        month: '*'
        weekday: '4'
        user: root
        job: "/home/vagrant/cfile.sh"
