Vagrant.configure("2") do |config|

  # Configuration for VM1
  config.vm.define "vm01" do |vm01|
    vm01.vm.box = "geerlingguy/centos7"
	  vm01.vm.network "private_network", ip: "192.168.40.20"
  	vm01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	   vb.cpus = 2
  end

    vm01.vm.provision "shell", inline: <<-SHELL
      # sudo yum clean all
      sudo yum install epel-release
      sudo yum install ansible -y
      sudo yum install ansible-doc -y
      SHELL
    end

    config.vm.define "vm02" do |vm02|
      vm02.vm.box = "geerlingguy/centos7"
      vm02.vm.network "private_network", ip: "192.168.40.21"
      vm02.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
       vb.cpus = 2
      end
  
      vm02.vm.provision "shell", inline: <<-SHELL
        SHELL
      end

    
    config.vm.define "vm03" do |vm03|
      vm03.vm.box = "geerlingguy/centos7"
      vm03.vm.network "private_network", ip: "192.168.40.22"
      vm03.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end
    
      vm03.vm.provision "shell", inline: <<-SHELL
        SHELL
      end

end
