---
- name: Install Apache Webserver
  hosts: localhost
  tasks:
    - name: Install Apache on Ubuntu Server
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install httpd on CentOS Server
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

