---
- name: Create users thru loop
  hosts: localhost
  vars:
    users: [john23, emma34, angela100]

  tasks:
    - name: Create users
      user:
        name: "{{item}}"
      with_items: "{{users}}"