---
- name: Add or update user password
  hosts: all
  
  tasks:
  - name: Change “george” password
    user:
      name: george
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"


      # ansible-playbook --check /etc/ansible/playbooks/add-update-user-password-remotely.yml --extra-vars newpassword=abc123